[0m22:08:41.122396 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff74579bcb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff7458a3980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff745799e80>]}


============================== 22:08:41.125518 | faacb478-58f9-4cc9-be57-c12042dc418e ==============================
[0m22:08:41.125518 [info ] [MainThread]: Running with dbt=1.8.5
[0m22:08:41.126337 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init example_dbt_core', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:08:41.139474 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/root/.dbt')}
[0m22:08:41.140022 [info ] [MainThread]: Creating dbt configuration folder at 
[0m22:08:41.141856 [debug] [MainThread]: Starter project path: /usr/local/lib/python3.12/dist-packages/dbt/include/starter_project
[0m22:08:41.145835 [info ] [MainThread]: 
Your new dbt project "example_dbt_core" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:08:41.146321 [info ] [MainThread]: Setting up your profile.
[0m22:08:41.147286 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m22:08:41.148358 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 0.08100476, "process_user_time": 1.476133, "process_kernel_time": 0.158211, "process_mem_max_rss": "86344", "process_out_blocks": "256", "command_success": false, "process_in_blocks": "0"}
[0m22:08:41.148906 [debug] [MainThread]: Command `dbt init` failed at 22:08:41.148744 after 0.08 seconds
[0m22:08:41.149376 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff746098560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff74556cfe0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff74552c290>]}
[0m22:08:41.149979 [debug] [MainThread]: Flushing usage events
